"""add_solar_system_tables

Revision ID: 2c269a01fd2c
Revises: 3ead24f5d6ae
Create Date: 2026-07-26 10:46:47.487004
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c269a01fd2c'
down_revision: Union[str, None] = '3ead24f5d6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('diameter_km', sa.Float(), nullable=True),
    sa.Column('mass', sa.String(length=100), nullable=True),
    sa.Column('gravity', sa.Float(), nullable=True),
    sa.Column('escape_velocity', sa.Float(), nullable=True),
    sa.Column('orbital_period', sa.Float(), nullable=True),
    sa.Column('rotation_period', sa.Float(), nullable=True),
    sa.Column('average_temperature', sa.Float(), nullable=True),
    sa.Column('distance_from_sun', sa.Float(), nullable=True),
    sa.Column('number_of_moons', sa.Integer(), nullable=False),
    sa.Column('atmosphere', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('texture_url', sa.String(length=512), nullable=True),
    sa.Column('model_url', sa.String(length=512), nullable=True),
    sa.Column('is_habitable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planets'))
    )
    op.create_index(op.f('ix_planets_is_habitable'), 'planets', ['is_habitable'], unique=False)
    op.create_index(op.f('ix_planets_name'), 'planets', ['name'], unique=True)
    op.create_index(op.f('ix_planets_slug'), 'planets', ['slug'], unique=True)
    op.create_table('moons',
    sa.Column('planet_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('orbital_period', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name=op.f('fk_moons_planet_id_planets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moons'))
    )
    op.create_index(op.f('ix_moons_name'), 'moons', ['name'], unique=True)
    op.create_index(op.f('ix_moons_planet_id'), 'moons', ['planet_id'], unique=False)
    op.create_index(op.f('ix_moons_slug'), 'moons', ['slug'], unique=True)
    op.create_table('planet_facts',
    sa.Column('planet_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name=op.f('fk_planet_facts_planet_id_planets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planet_facts'))
    )
    op.create_index(op.f('ix_planet_facts_display_order'), 'planet_facts', ['display_order'], unique=False)
    op.create_index(op.f('ix_planet_facts_planet_id'), 'planet_facts', ['planet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planet_facts_planet_id'), table_name='planet_facts')
    op.drop_index(op.f('ix_planet_facts_display_order'), table_name='planet_facts')
    op.drop_table('planet_facts')
    op.drop_index(op.f('ix_moons_slug'), table_name='moons')
    op.drop_index(op.f('ix_moons_planet_id'), table_name='moons')
    op.drop_index(op.f('ix_moons_name'), table_name='moons')
    op.drop_table('moons')
    op.drop_index(op.f('ix_planets_slug'), table_name='planets')
    op.drop_index(op.f('ix_planets_name'), table_name='planets')
    op.drop_index(op.f('ix_planets_is_habitable'), table_name='planets')
    op.drop_table('planets')
    # ### end Alembic commands ###
