"""add_space_timeline_tables

Revision ID: 3ead24f5d6ae
Revises: b63afa163cfd
Create Date: 2026-07-26 10:21:44.510116
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ead24f5d6ae'
down_revision: Union[str, None] = 'b63afa163cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eras',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_year', sa.BigInteger(), nullable=True),
    sa.Column('end_year', sa.BigInteger(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eras'))
    )
    op.create_index(op.f('ix_eras_name'), 'eras', ['name'], unique=True)
    op.create_index(op.f('ix_eras_slug'), 'eras', ['slug'], unique=True)
    op.create_table('timeline_events',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('event_date', sa.String(length=100), nullable=True),
    sa.Column('year', sa.BigInteger(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('thumbnail', sa.String(length=512), nullable=True),
    sa.Column('era_id', sa.UUID(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_timeline_events_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['era_id'], ['eras.id'], name=op.f('fk_timeline_events_era_id_eras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    op.create_index(op.f('ix_timeline_events_era_id'), 'timeline_events', ['era_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_importance'), 'timeline_events', ['importance'], unique=False)
    op.create_index(op.f('ix_timeline_events_is_featured'), 'timeline_events', ['is_featured'], unique=False)
    op.create_index(op.f('ix_timeline_events_slug'), 'timeline_events', ['slug'], unique=True)
    op.create_index(op.f('ix_timeline_events_title'), 'timeline_events', ['title'], unique=False)
    op.create_index(op.f('ix_timeline_events_year'), 'timeline_events', ['year'], unique=False)
    op.create_table('event_media',
    sa.Column('timeline_event_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['timeline_event_id'], ['timeline_events.id'], name=op.f('fk_event_media_timeline_event_id_timeline_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_media'))
    )
    op.create_index(op.f('ix_event_media_timeline_event_id'), 'event_media', ['timeline_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_media_timeline_event_id'), table_name='event_media')
    op.drop_table('event_media')
    op.drop_index(op.f('ix_timeline_events_year'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_title'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_slug'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_is_featured'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_importance'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_era_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_eras_slug'), table_name='eras')
    op.drop_index(op.f('ix_eras_name'), table_name='eras')
    op.drop_table('eras')
    # ### end Alembic commands ###
