"""add_mission_tracking_tables

Revision ID: 98b3034efbd2
Revises: 2c269a01fd2c
Create Date: 2026-07-26 13:50:31.651917
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b3034efbd2'
down_revision: Union[str, None] = '2c269a01fd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agencies'))
    )
    op.create_index(op.f('ix_agencies_name'), 'agencies', ['name'], unique=True)
    op.create_index(op.f('ix_agencies_slug'), 'agencies', ['slug'], unique=True)
    op.create_table('missions',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('mission_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('spacecraft', sa.String(length=150), nullable=True),
    sa.Column('rocket', sa.String(length=150), nullable=True),
    sa.Column('launch_site', sa.String(length=255), nullable=True),
    sa.Column('launch_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('mission_patch', sa.String(length=512), nullable=True),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('livestream_url', sa.String(length=512), nullable=True),
    sa.Column('wikipedia_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_missions_agency_id_agencies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missions'))
    )
    op.create_index(op.f('ix_missions_agency_id'), 'missions', ['agency_id'], unique=False)
    op.create_index(op.f('ix_missions_destination'), 'missions', ['destination'], unique=False)
    op.create_index(op.f('ix_missions_is_featured'), 'missions', ['is_featured'], unique=False)
    op.create_index(op.f('ix_missions_launch_date'), 'missions', ['launch_date'], unique=False)
    op.create_index(op.f('ix_missions_mission_type'), 'missions', ['mission_type'], unique=False)
    op.create_index(op.f('ix_missions_name'), 'missions', ['name'], unique=False)
    op.create_index(op.f('ix_missions_slug'), 'missions', ['slug'], unique=True)
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_table('mission_media',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('fk_mission_media_mission_id_missions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_media'))
    )
    op.create_index(op.f('ix_mission_media_mission_id'), 'mission_media', ['mission_id'], unique=False)
    op.create_table('mission_milestones',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('milestone_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('fk_mission_milestones_mission_id_missions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_milestones'))
    )
    op.create_index(op.f('ix_mission_milestones_display_order'), 'mission_milestones', ['display_order'], unique=False)
    op.create_index(op.f('ix_mission_milestones_mission_id'), 'mission_milestones', ['mission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mission_milestones_mission_id'), table_name='mission_milestones')
    op.drop_index(op.f('ix_mission_milestones_display_order'), table_name='mission_milestones')
    op.drop_table('mission_milestones')
    op.drop_index(op.f('ix_mission_media_mission_id'), table_name='mission_media')
    op.drop_table('mission_media')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_index(op.f('ix_missions_slug'), table_name='missions')
    op.drop_index(op.f('ix_missions_name'), table_name='missions')
    op.drop_index(op.f('ix_missions_mission_type'), table_name='missions')
    op.drop_index(op.f('ix_missions_launch_date'), table_name='missions')
    op.drop_index(op.f('ix_missions_is_featured'), table_name='missions')
    op.drop_index(op.f('ix_missions_destination'), table_name='missions')
    op.drop_index(op.f('ix_missions_agency_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_agencies_slug'), table_name='agencies')
    op.drop_index(op.f('ix_agencies_name'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
