"""add_analytics_metrics_tables

Revision ID: c5750bc49a4c
Revises: afa2f0434b96
Create Date: 2026-07-26 18:17:25.985411
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5750bc49a4c'
down_revision: Union[str, None] = 'afa2f0434b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_analytics',
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('bookmarks', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('average_read_time', sa.Float(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_analytics'))
    )
    op.create_index(op.f('ix_content_analytics_resource_id'), 'content_analytics', ['resource_id'], unique=False)
    op.create_index(op.f('ix_content_analytics_resource_type'), 'content_analytics', ['resource_type'], unique=False)
    op.create_table('daily_analytics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('stories_read', sa.Integer(), nullable=False),
    sa.Column('missions_viewed', sa.Integer(), nullable=False),
    sa.Column('timeline_views', sa.Integer(), nullable=False),
    sa.Column('planet_views', sa.Integer(), nullable=False),
    sa.Column('searches', sa.Integer(), nullable=False),
    sa.Column('ai_questions', sa.Integer(), nullable=False),
    sa.Column('notifications_sent', sa.Integer(), nullable=False),
    sa.Column('notifications_opened', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_analytics'))
    )
    op.create_index(op.f('ix_daily_analytics_date'), 'daily_analytics', ['date'], unique=True)
    op.create_table('analytics_events',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('referrer', sa.String(length=255), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analytics_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events'))
    )
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_resource_id'), 'analytics_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_resource_type'), 'analytics_events', ['resource_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_resource_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_resource_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_daily_analytics_date'), table_name='daily_analytics')
    op.drop_table('daily_analytics')
    op.drop_index(op.f('ix_content_analytics_resource_type'), table_name='content_analytics')
    op.drop_index(op.f('ix_content_analytics_resource_id'), table_name='content_analytics')
    op.drop_table('content_analytics')
    # ### end Alembic commands ###
