"""add_story_search_personalization_tables

Revision ID: e808dc28a5c7
Revises: 98b3034efbd2
Create Date: 2026-07-26 14:04:39.515711
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e808dc28a5c7'
down_revision: Union[str, None] = '98b3034efbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_categories'))
    )
    op.create_index(op.f('ix_story_categories_name'), 'story_categories', ['name'], unique=True)
    op.create_index(op.f('ix_story_categories_slug'), 'story_categories', ['slug'], unique=True)
    op.create_table('story_tags',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_tags'))
    )
    op.create_index(op.f('ix_story_tags_name'), 'story_tags', ['name'], unique=True)
    op.create_index(op.f('ix_story_tags_slug'), 'story_tags', ['slug'], unique=True)
    op.create_table('stories',
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('estimated_read_time', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('story_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['story_categories.id'], name=op.f('fk_stories_category_id_story_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    op.create_index(op.f('ix_stories_category_id'), 'stories', ['category_id'], unique=False)
    op.create_index(op.f('ix_stories_difficulty'), 'stories', ['difficulty'], unique=False)
    op.create_index(op.f('ix_stories_is_featured'), 'stories', ['is_featured'], unique=False)
    op.create_index(op.f('ix_stories_published_at'), 'stories', ['published_at'], unique=False)
    op.create_index(op.f('ix_stories_slug'), 'stories', ['slug'], unique=True)
    op.create_index(op.f('ix_stories_status'), 'stories', ['status'], unique=False)
    op.create_index(op.f('ix_stories_story_type'), 'stories', ['story_type'], unique=False)
    op.create_index(op.f('ix_stories_title'), 'stories', ['title'], unique=False)
    op.create_index(op.f('ix_stories_view_count'), 'stories', ['view_count'], unique=False)
    op.create_table('bookmarks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookmarks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmarks'))
    )
    op.create_index(op.f('ix_bookmarks_resource_id'), 'bookmarks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_resource_type'), 'bookmarks', ['resource_type'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('collections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    op.create_index(op.f('ix_collections_is_public'), 'collections', ['is_public'], unique=False)
    op.create_index(op.f('ix_collections_title'), 'collections', ['title'], unique=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history'))
    )
    op.create_index(op.f('ix_search_history_keyword'), 'search_history', ['keyword'], unique=False)
    op.create_index(op.f('ix_search_history_module'), 'search_history', ['module'], unique=False)
    op.create_index(op.f('ix_search_history_searched_at'), 'search_history', ['searched_at'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('story_chapters',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('estimated_read_time', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_chapters_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_chapters'))
    )
    op.create_index(op.f('ix_story_chapters_chapter_number'), 'story_chapters', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_story_chapters_story_id'), 'story_chapters', ['story_id'], unique=False)
    op.create_table('story_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('last_chapter', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_progress_story_id_stories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_story_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_progress'))
    )
    op.create_index(op.f('ix_story_progress_completed'), 'story_progress', ['completed'], unique=False)
    op.create_index(op.f('ix_story_progress_story_id'), 'story_progress', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_progress_user_id'), 'story_progress', ['user_id'], unique=False)
    op.create_table('story_tag_association',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_tag_association_story_id_stories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['story_tags.id'], name=op.f('fk_story_tag_association_tag_id_story_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'tag_id', name=op.f('pk_story_tag_association'))
    )
    op.create_table('user_activities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_activities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activities'))
    )
    op.create_index(op.f('ix_user_activities_action'), 'user_activities', ['action'], unique=False)
    op.create_index(op.f('ix_user_activities_resource_id'), 'user_activities', ['resource_id'], unique=False)
    op.create_index(op.f('ix_user_activities_resource_type'), 'user_activities', ['resource_type'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    op.create_table('collection_items',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_items_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_items'))
    )
    op.create_index(op.f('ix_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_items_display_order'), 'collection_items', ['display_order'], unique=False)
    op.create_index(op.f('ix_collection_items_resource_id'), 'collection_items', ['resource_id'], unique=False)
    op.create_index(op.f('ix_collection_items_resource_type'), 'collection_items', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_items_resource_type'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_resource_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_display_order'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_collection_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_resource_type'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_resource_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_action'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_table('story_tag_association')
    op.drop_index(op.f('ix_story_progress_user_id'), table_name='story_progress')
    op.drop_index(op.f('ix_story_progress_story_id'), table_name='story_progress')
    op.drop_index(op.f('ix_story_progress_completed'), table_name='story_progress')
    op.drop_table('story_progress')
    op.drop_index(op.f('ix_story_chapters_story_id'), table_name='story_chapters')
    op.drop_index(op.f('ix_story_chapters_chapter_number'), table_name='story_chapters')
    op.drop_table('story_chapters')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_searched_at'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_module'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_keyword'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_title'), table_name='collections')
    op.drop_index(op.f('ix_collections_is_public'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_resource_type'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_resource_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_stories_view_count'), table_name='stories')
    op.drop_index(op.f('ix_stories_title'), table_name='stories')
    op.drop_index(op.f('ix_stories_story_type'), table_name='stories')
    op.drop_index(op.f('ix_stories_status'), table_name='stories')
    op.drop_index(op.f('ix_stories_slug'), table_name='stories')
    op.drop_index(op.f('ix_stories_published_at'), table_name='stories')
    op.drop_index(op.f('ix_stories_is_featured'), table_name='stories')
    op.drop_index(op.f('ix_stories_difficulty'), table_name='stories')
    op.drop_index(op.f('ix_stories_category_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_story_tags_slug'), table_name='story_tags')
    op.drop_index(op.f('ix_story_tags_name'), table_name='story_tags')
    op.drop_table('story_tags')
    op.drop_index(op.f('ix_story_categories_slug'), table_name='story_categories')
    op.drop_index(op.f('ix_story_categories_name'), table_name='story_categories')
    op.drop_table('story_categories')
    # ### end Alembic commands ###
